/**
 * Init Command
 * Interactive setup wizard for V4V Analytics
 */

import fs from 'fs';
import path from 'path';
import { input, password, confirm } from '@inquirer/prompts';
import { CONFIG } from '../config.js';
import { logger } from '../logger.js';
import { success, error, warning, dim, bold, cyan } from '../colors.js';
import { validateNwcString } from '../validation.js';

/**
 * Test NWC connection by fetching one transaction
 */
async function testConnection(nwcString) {
  const { NWCClient } = await import('@getalby/sdk');

  logger.debug('Testing NWC connection');

  const client = new NWCClient({
    nostrWalletConnectUrl: nwcString,
    timeout: 30000,
  });

  try {
    const response = await client.listTransactions({ type: 'incoming', limit: 1 });
    return { success: true, hasTransactions: response.transactions?.length > 0 };
  } catch (err) {
    logger.debug('NWC connection test failed', { error: err.message });
    return { success: false, error: err.message };
  } finally {
    client.close();
  }
}

/**
 * Count V4V payments for a given site URL
 */
async function countV4VPayments(nwcString, siteUrl) {
  const { NWCClient } = await import('@getalby/sdk');

  logger.debug('Counting V4V payments', { siteUrl });

  const client = new NWCClient({
    nostrWalletConnectUrl: nwcString,
    timeout: 60000,
  });

  try {
    let count = 0;
    let offset = 0;
    const limit = 50;

    // Fetch up to 200 transactions to count V4V payments
    for (let i = 0; i < 4; i++) {
      const response = await client.listTransactions({ type: 'incoming', limit, offset });
      if (!response.transactions?.length) break;

      for (const tx of response.transactions) {
        if (tx.description?.includes(siteUrl)) {
          count++;
        }
      }

      if (response.transactions.length < limit) break;
      offset += limit;
    }

    logger.debug('V4V payment count', { count });
    return count;
  } finally {
    client.close();
  }
}

/**
 * Execute init command
 */
export async function initCommand() {
  console.log(bold('\nV4V Analytics Setup\n'));
  console.log(dim('This wizard will help you configure V4V Analytics.\n'));

  const envPath = path.join(CONFIG.paths.root, '.env');
  const envExists = fs.existsSync(envPath);

  if (envExists) {
    console.log(warning('An existing .env file was found.\n'));
    const overwrite = await confirm({
      message: 'Do you want to update it?',
      default: false,
    });
    if (!overwrite) {
      console.log(dim('\nSetup cancelled.'));
      return;
    }
    console.log('');
  }

  // Get NWC connection string
  console.log(dim('Get your NWC connection string from:'));
  console.log(dim('  Alby Hub > Apps > Create new app\n'));

  const nwcString = await password({
    message: 'NWC Connection String:',
    mask: '*',
    validate: (value) => {
      if (!value) return 'Connection string is required';
      try {
        validateNwcString(value);
      } catch (err) {
        return err.message;
      }
      return true;
    },
  });

  // Test NWC connection
  console.log(dim('\nTesting NWC connection...'));
  const connResult = await testConnection(nwcString);

  if (!connResult.success) {
    console.log(error(`\nConnection failed: ${connResult.error}`));
    console.log(dim('\nPlease check your connection string and try again.'));
    process.exit(1);
  }

  console.log(success('Connected successfully!\n'));

  // Get site URL
  const siteUrl = await input({
    message: 'Your site URL (without https://):',
    default: CONFIG.siteUrl || '',
    validate: (value) => {
      if (!value) return 'Site URL is required';
      if (value.startsWith('http://') || value.startsWith('https://')) {
        return 'Enter without protocol (e.g., example.com)';
      }
      return true;
    },
  });

  // Count V4V payments
  console.log(dim('\nLooking for V4V payments...'));
  const paymentCount = await countV4VPayments(nwcString, siteUrl);

  if (paymentCount > 0) {
    console.log(success(`Found ${cyan(paymentCount.toString())} V4V payments!\n`));
  } else {
    console.log(warning('No V4V payments found yet.\n'));
    console.log(dim('This is normal if you just set up V4V on your site.'));
    console.log(dim('Payments will appear once visitors start tipping.\n'));
  }

  // Optional: RSS URL
  const customRss = await confirm({
    message: 'Do you want to set a custom RSS feed URL?',
    default: false,
  });

  let rssUrl = null;
  if (customRss) {
    rssUrl = await input({
      message: 'RSS Feed URL:',
      default: `https://${siteUrl}/feed.xml`,
    });
  }

  // Write .env file
  let envContent = `# V4V Analytics Configuration
# Generated by v4v init

NWC_CONNECTION_STRING=${nwcString}
V4V_SITE_URL=${siteUrl}
`;

  if (rssUrl) {
    envContent += `V4V_RSS_URL=${rssUrl}\n`;
  }

  fs.writeFileSync(envPath, envContent);
  console.log(success(`\nConfiguration saved to ${dim('.env')}`));

  console.log(bold('\nYou\'re all set! Try these commands:\n'));
  console.log(dim('  v4v report           ') + 'Generate a payment report');
  console.log(dim('  v4v report --by-essay') + 'See payments by essay');
  console.log(dim('  v4v dashboard        ') + 'Start the web dashboard');
  console.log(dim('  v4v status           ') + 'Check connection status');
  console.log('');
}
